# Generated by Django 6.0.4 on 2026-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
