# Generated by Django 5.2.6 on 2026-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0002_portfolio_github_link_portfolio_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='template',
            field=models.CharField(choices=[('starter', 'Starter'), ('gradient_aurora', 'Gradient Aurora'), ('minimal_mono', 'Minimal Mono'), ('creative_splash', 'Creative Splash'), ('elegant', 'Elegant'), ('developer', 'Developer')], default='starter', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tech tags', max_length=300, null=True),
        ),
    ]
