# Generated by Django 5.2.6 on 2026-08-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0003_portfolio_email_portfolio_skills_portfolio_tagline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='accent_color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='animation_style',
            field=models.CharField(default='fade', max_length=30),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='font_family',
            field=models.CharField(default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='layout_style',
            field=models.CharField(default='modern', max_length=30),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='professional_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='section_order',
            field=models.CharField(default='education,experience,projects,certificates', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.CharField(choices=[('minimal_developer', 'Minimal Developer'), ('software_engineer', 'Software Engineer'), ('ai_engineer', 'AI Engineer'), ('student_portfolio', 'Student Portfolio'), ('creative_portfolio', 'Creative Portfolio'), ('starter', 'Starter'), ('gradient_aurora', 'Gradient Aurora'), ('minimal_mono', 'Minimal Mono'), ('creative_splash', 'Creative Splash'), ('elegant', 'Elegant'), ('developer', 'Developer')], default='minimal_developer', max_length=30),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='builder_app.portfolio')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='builder_app.portfolio')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='builder_app.portfolio')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
